// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr1kzJ5paBYBPDvY2oKFJ07BN1MuwH2nk',
    appId: '1:7970221337:web:e025b33186a61444f8a988',
    messagingSenderId: '7970221337',
    projectId: 'eshop-34b87',
    authDomain: 'eshop-34b87.firebaseapp.com',
    storageBucket: 'eshop-34b87.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPDDvt66HavK4lZUaInUHbX2l_1RThH6s',
    appId: '1:7970221337:android:64f64c027b646357f8a988',
    messagingSenderId: '7970221337',
    projectId: 'eshop-34b87',
    storageBucket: 'eshop-34b87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwIiGdW3W76tJIX51Sqql-J5oa_2tqd1g',
    appId: '1:7970221337:ios:83524a7ae42efa06f8a988',
    messagingSenderId: '7970221337',
    projectId: 'eshop-34b87',
    storageBucket: 'eshop-34b87.firebasestorage.app',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwIiGdW3W76tJIX51Sqql-J5oa_2tqd1g',
    appId: '1:7970221337:ios:83524a7ae42efa06f8a988',
    messagingSenderId: '7970221337',
    projectId: 'eshop-34b87',
    storageBucket: 'eshop-34b87.firebasestorage.app',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr1kzJ5paBYBPDvY2oKFJ07BN1MuwH2nk',
    appId: '1:7970221337:web:74267135c33590fbf8a988',
    messagingSenderId: '7970221337',
    projectId: 'eshop-34b87',
    authDomain: 'eshop-34b87.firebaseapp.com',
    storageBucket: 'eshop-34b87.firebasestorage.app',
  );
}
